erp/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'erp'
urlpatterns = [
	
	
    url(r'^$', views.index, name='index'),

    url(r'^misfacturas/$', views.FacturasByUserListView.as_view(), name='mis-facturas'),
    
    
    url(r'^trabajos/$', views.ListarTrabajosView.as_view(), name='trabajos'),
    url(r'^trabajos/ot/new/$', views.ot_new, name='ot_new'),
    url(r'^trabajos/ot/edit/(?P<pk>[0-9]+)/$', views.ot_new, name='ot_new'),


    url(r'^cotizaciones/$', views.ListarCotizacionView.as_view(), name='cotizaciones'),
	url(r'^cotizacion/new/$', views.cotizacion_new, name='cotizacion_new'),
    url(r'^cotizacion/new/documents/(?P<cotizacion_id>[0-9]+)/$', views.documentacion_new, name='cotizacion_new_documents'),
	url(r'^cotizacion/edit/(?P<cotizacion_id>[0-9]+)/$', views.cotizacion_new, name='cotizacion_edit'),
    url(r'^cotizacion/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='cotizacion_detail'),
    url(r'^cotizacion/trabajos/([\w-]+)/$', views.ListarTrabajoCotizacionView.as_view(), name='cotizacion_trabajos'),

    url(r'^factura/new/$', views.factura_new, name='factura_new'),
    url(r'^factura/edit/(?P<factura_id>[0-9]+)/$', views.factura_new, name='factura_new'),
    url(r'^factura/cotizaciones/([\w-]+)/$', views.ListarCotizacionesFacturaView.as_view(), name='cotizaciones_factura'),
    url(r'^facturas/$', views.ListarFacturaView.as_view(), name='facturas'),

    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<cliente_id>[0-9]+)/vote/$', views.vote, name='vote'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Prueba

italuzbi/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
	url(r'^accounts/', include('django.contrib.auth.urls')),
	url(r'^erp/', include('erp.urls')),
    url(r'^admin/', admin.site.urls),
] 

erp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.forms import inlineformset_factory, formset_factory, modelformset_factory

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy




from .forms import CotizacionForm, TrabajoForm, TrabajoFormSet, DocumentacionForm, DocumentacionFormset, FacturaModelForm, OtForm, TrabajoOTFormSet


from .models import Cliente, Factura, Trabajo, Cotizacion, Documentacion, Documento, OT


@login_required
def index(request):
    
    template = loader.get_template('erp/index.html')


    return HttpResponse(template.render(request))


# ********************************************************************************************************************************************

class FacturasByUserListView(LoginRequiredMixin,generic.ListView):
    """
    Generic class-based view listing books on loan to current user. 
    """
    model = Factura
    template_name ='erp/facturas_por_usuario.html'
    paginate_by = 30
    
    def get_queryset(self):
        return Factura.objects.filter(created_by=self.request.user).filter(estado__exact='1').order_by('fecha')

# ********************************************************************************************************************************************

class ListarTrabajosView(LoginRequiredMixin,generic.ListView):
    model = Trabajo
    template_name = 'erp/trabajos.html'
    paginate_by = 30

# ********************************************************************************************************************************************

class ListarCotizacionesFacturaView(LoginRequiredMixin,generic.ListView):
    template_name = 'erp/cotizaciones.html'
    paginate_by = 30
    def get_queryset(self):
        self.factura = get_object_or_404(Factura, id=self.args[0]) # Es para darle el argumento de la factura.
        return self.factura.cotizaciones.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ListarCotizacionesFacturaView, self).get_context_data(**kwargs)
        # Add in the factura
        context['factura'] = self.factura
        return context
 
# ********************************************************************************************************************************************       

class ListarTrabajoCotizacionView(LoginRequiredMixin,generic.ListView):

    template_name = 'erp/trabajos.html'
    paginate_by = 30
    
    def get_queryset(self):
        self.cotizacion = get_object_or_404(Cotizacion, id=self.args[0]) # Es para darle el argumento de la cotizacion.
        return Trabajo.objects.filter(cotizacion=self.cotizacion)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ListarTrabajoCotizacionView, self).get_context_data(**kwargs)
        # Add in the factura
        context['cotizacion'] = self.cotizacion
        return context
 
# ******************************************************************************************************************************************** 

class ListarCotizacionView(LoginRequiredMixin,generic.ListView):
    model = Cotizacion
    template_name = 'erp/cotizaciones.html'
    paginate_by = 30
    ordering = ["-pk"]

# ********************************************************************************************************************************************

class ListarFacturaView(LoginRequiredMixin,generic.ListView):
    model = Factura
    template_name = 'erp/facturas.html'
    paginate_by = 30


# ********************************************************************************************************************************************
# CREAR FACTURA
# ********************************************************************************************************************************************

def factura_new(request, factura_id=None, *args, **kwargs):
    if factura_id:
        instancia = Factura.objects.get(pk=factura_id)
    else:
        instancia = Factura()
    form = FacturaModelForm(request.POST or None, prefix='factura',instance=instancia)
    if form.is_valid():
        form.save()
        for cotizacion in instancia.cotizaciones.all():
            cotizacion.estado_cotizacion = 4
            cotizacion.save()
        return redirect('erp:facturas')
    return render(request, 'erp/factura_form.html', {'form': form})

# ********************************************************************************************************************************************
# CREAR ORDEN DE TRABAJO
# ********************************************************************************************************************************************

def ot_new(request, pk=None, *args, **kwargs):

    template = 'erp/ot_form.html'
    if pk:
        instancia = OT.objects.get(pk=pk)
        trabajo_list = Trabajo.objects.filter(ot=pk)
    else:
        instancia = OT()
        trabajo_list = Trabajo.objects.exclude(ot__isnull=False)
    form = OtForm(request.POST or None, prefix='ot', instance=instancia)

    if form.is_valid():
        form.save()
        seleccion = request.POST.getlist('checks')
        for x in seleccion:
            trabajo_selected = Trabajo.objects.get(pk=x)
            trabajo_selected.ot = instancia
            trabajo_selected.save()
            if trabajo_selected.cotizacion.trabajos_pendientes > 0:
                print "Hay trabajos pendientes"
            else:
                print "No hay trabajos pendientes"
                trabajo_selected.cotizacion.estado_cotizacion = 2
                trabajo_selected.cotizacion.save()

        return redirect('erp:trabajos')
    context = {'form': form , 'trabajo_list': trabajo_list}
    return render(request, template, context)

    

# ********************************************************************************************************************************************

def documentacion_new(request, cotizacion_id=None, *args, **kwargs):
    if cotizacion_id:
        docus = Cotizacion.objects.get(pk=cotizacion_id)
        formset = DocumentacionFormset(prefix='documentacion',instance=docus)
        if request.method == 'POST':
            formset = DocumentacionFormset(request.POST, request.FILES, prefix='documentacion', instance=docus)
            documentacion_valid = formset.is_valid()
            if documentacion_valid:
                formset.save()
                if docus.debe:
                        docus.estado_cotizacion = 3
                        docus.save()                
                return redirect('erp:cotizacion_detail', pk=cotizacion_id)
    return render(request, 'erp/documentacion_form.html', {'formset': formset, 'cotizacion': docus})

# ********************************************************************************************************************************************

def cotizacion_new(request, cotizacion_id=None, *args, **kwargs):
    if cotizacion_id:
        editar = Cotizacion.objects.get(pk=cotizacion_id)
    else:
        editar = Cotizacion()
    if request.method == 'POST':
        cotizacion_form = CotizacionForm(request.POST, request.FILES, prefix='cotizacion', instance=editar)
        trabajo_forms = TrabajoFormSet(request.POST, request.FILES, prefix='trabajo', instance=editar)
        cotizacion_valid = cotizacion_form.is_valid()
        trabajo_valid = trabajo_forms.is_valid()
        if cotizacion_valid and trabajo_valid:
            cotizacion = cotizacion_form.save()
            trabajo_forms.instance = cotizacion
            trabajo_forms.save()
            if not editar.tiene_documento:
                for doc in Documento.objects.filter(cliente=cotizacion.local.cliente):
                    Documentacion.objects.create(cotizacion_id=cotizacion.pk, documento_id=doc.pk)    
            return redirect('erp:cotizacion_detail', pk=cotizacion.pk)
    else:
        cotizacion_form = CotizacionForm(prefix='cotizacion', instance=editar)
        trabajo_forms = TrabajoFormSet(prefix='trabajo', instance=editar)
    return render(request, 'erp/cotizacion_edit.html', {'cotizacion_form': cotizacion_form, 'trabajo_forms': trabajo_forms})

# ********************************************************************************************************************************************

class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Cotizacion
    template_name = 'erp/detail.html'



class ResultsView(generic.DetailView):
    model = Cliente
    template_name = 'erp/results.html'


def vote(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    try:
        selected_factura = cliente.factura_set.get(pk=request.POST['factura'])
    except (KeyError, Factura.DoesNotExist):
        # Redisplay the cliente voting form.
        return render(request, 'erp/detail.html', {
            'cliente': cliente,
            'error_message': "You didn't select a factura.",
        })
    else:
        selected_factura.estado = 'pagada'
        selected_factura.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('erp:results', args=(cliente.id,)))

erp/templates/base_generic.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="">
<head>
	<meta charset="utf-8" />
	<title>Servicios Italuz | ERP</title>
	<meta name="description" content="app, web app, responsive, responsive layout, admin, admin panel, admin dashboard, flat, flat ui, ui kit, AngularJS, ui route, charts, widgets, components" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
	<link rel="stylesheet" href="{% static 'libs/assets/animate.css/animate.css' %}" type="text/css" />
	<link rel="stylesheet" href="{% static 'libs/assets/font-awesome/css/font-awesome.min.css' %}" type="text/css" />
	<link rel="stylesheet" href="{% static 'libs/assets/simple-line-icons/css/simple-line-icons.css' %}" type="text/css" />
	<link rel="stylesheet" href="{% static 'libs/jquery/bootstrap/dist/css/bootstrap.css' %}" type="text/css" />
	<link rel="stylesheet" href="{% static 'libs/jquery/bootstrap-datepicker/css/bootstrap-datepicker3.css' %}" type="text/css" />
	<link rel="stylesheet" href="{% static 'erp/css/font.css' %}" type="text/css" />
	<link rel="stylesheet" href="{% static 'erp/css/app.css' %}" type="text/css" />



	{% block styles %}{% endblock styles %}

</head>
<body>

<style type="text/css" media="print">
.dontprint
{ display: none; }
</style>


	<div class="app app-header-fixed ">


		<!-- header -->
		<header id="header" class="app-header navbar" role="menu">
			<!-- navbar header -->
			<div class="navbar-header bg-dark">
				<button class="pull-right visible-xs dk" ui-toggle-class="show" target=".navbar-collapse">
					<i class="glyphicon glyphicon-cog"></i>
				</button>
				<button class="pull-right visible-xs" ui-toggle-class="off-screen" target=".app-aside" ui-scroll="app">
					<i class="glyphicon glyphicon-align-justify"></i>
				</button>
				<!-- brand -->
				<a href="#/" class="navbar-brand text-lt">
					<i class="fa fa-cogs"></i>
					<img src="{% static 'erp/img/logo.png' %}" alt="." class="hide">
					<span class="hidden-folded m-l-xs">Italuz ERP</span>
				</a>
				<!-- / brand -->
			</div>
			<!-- / navbar header -->

			<!-- navbar collapse -->
			<div class="collapse pos-rlt navbar-collapse box-shadow bg-white-only">
				<!-- buttons -->
				<div class="nav navbar-nav hidden-xs">
					<a href="#" class="btn no-shadow navbar-btn" ui-toggle-class="app-aside-folded" target=".app">
						<i class="fa fa-dedent fa-fw text"></i>
						<i class="fa fa-indent fa-fw text-active"></i>
					</a>

				</div>
				<!-- / buttons -->

				<!-- link and dropdown -->
				<ul class="nav navbar-nav hidden-sm">
					<li class="dropdown pos-stc">
						<h3>{% block title %}  {% endblock %}</h3>

					</li>

				</ul>
				<!-- / link and dropdown -->



				<!-- nabar right -->
				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" data-toggle="dropdown" class="dropdown-toggle">
							<i class="icon-bell fa-fw"></i>
							<span class="visible-xs-inline">Notifications</span>
							<span class="badge badge-sm up bg-danger pull-right-xs">2</span>
						</a>
						<!-- dropdown -->
						<div class="dropdown-menu w-xl animated fadeInUp">
							<div class="panel bg-white">
								<div class="panel-heading b-light bg-light">
									<strong>You have <span>2</span> notifications</strong>
								</div>
								<div class="list-group">
									<a href class="list-group-item">
										<span class="pull-left m-r thumb-sm">
											<img src="{% static 'erp/img/a0.jpg' %}" alt="..." class="img-circle">
										</span>
										<span class="clear block m-b-none">
											Use awesome animate.css<br>
											<small class="text-muted">10 minutes ago</small>
										</span>
									</a>
									<a href class="list-group-item">
										<span class="clear block m-b-none">
											1.0 initial released<br>
											<small class="text-muted">1 hour ago</small>
										</span>
									</a>
								</div>
								<div class="panel-footer text-sm">
									<a href class="pull-right"><i class="fa fa-cog"></i></a>
									<a href="#notes" data-toggle="class:show animated fadeInRight">See all the notifications</a>
								</div>
							</div>
						</div>
						<!-- / dropdown -->
					</li>
					<li class="dropdown">
						<a href="#" data-toggle="dropdown" class="dropdown-toggle clear" data-toggle="dropdown">
							
							{% if user.is_authenticated %}
							<span class="hidden-sm hidden-md">{{ user.first_name }} {{ user.last_name }}</span> <b class="caret"></b>
						</a>

						<!-- dropdown -->
						<ul class="dropdown-menu animated fadeInRight w">
							<li>
								<a href="{% url 'logout'%}?next={{request.path}}">Logout</a>
							</li>
						</ul>
						{% else %}
						<span class="hidden-sm hidden-md">ERROR</span> <b class="caret"></b>
						<ul class="dropdown-menu animated fadeInRight w">
							<li>
								<a href="{% url 'login'%}?next={{request.path}}">Login</a>
							</li>
						</ul>
						{% endif %}
						<!-- / dropdown -->
					</li>
				</ul>
				<!-- / navbar right -->
			</div>
			<!-- / navbar collapse -->
		</header>
		<!-- / header -->


		<!-- aside -->
		<aside id="aside" class="app-aside hidden-xs bg-dark dontprint">
			<div class="aside-wrap">
				<div class="navi-wrap">

					
					<!-- nav -->
					<nav ui-nav class="navi clearfix">
						<ul class="nav">
							<li class="hidden-folded padder m-t m-b-sm text-muted text-xs">
								<span>Navigation</span>
							</li>
							<li>
								<a href class="auto">      
									<span class="pull-right text-muted">
										<i class="fa fa-fw fa-angle-right text"></i>
										<i class="fa fa-fw fa-angle-down text-active"></i>
									</span>
									<i class="fa fa-file-text-o icon text-primary"></i>
									<span class="font-bold">Cotizaciones</span>
								</a>
								<ul class="nav nav-sub dk">
									<li class="nav-sub-header">
										<a href>
											<span>Cotizaciones</span>
										</a>
									</li>
									<li>
										<a href="{% url 'erp:cotizacion_new' %}">
											<span>Crear</span>
										</a>
									</li>
									<li>
										<a href=" {% url 'erp:cotizaciones' %} ">
											<b class="label bg-info pull-right">{{contador_cotizaciones}}</b>
											<span>Cotizaciones</span>
										</a>

									</li>
									
								</ul>
								<li class="">
					                <a href="" class="auto">
					                  <span class="pull-right text-muted">
					                    <i class="fa fa-fw fa-angle-right text"></i>
					                    <i class="fa fa-fw fa-angle-down text-active"></i>
					                  </span>
					                  	<b class="badge bg-success pull-right">9</b>
										<i class="fa fa-usd icon text-success-lter"></i>
										<span class="font-bold">Facturas</span>
					                </a>
					                <ul class="nav nav-sub dk" style="display: none;">
					                  <li class="nav-sub-header">
					                    <a href="">
					                      <span>JoJOJOJ</span>
					                    </a>
					                  </li>
					                  <li>
					                    <a href="{% url 'erp:factura_new' %}">
					                      <span>Crear</span>
					                    </a>
					                  </li>
					                  <li>
					                    <a href="{% url 'erp:facturas' %}">
					                      <span>Listar</span>
					                    </a>
					                  </li>
					                </ul>
					            </li>
					            <li class="">
					                <a href="" class="auto">      
					                  <span class="pull-right text-muted">
					                    <i class="fa fa-fw fa-angle-right text"></i>
					                    <i class="fa fa-fw fa-angle-down text-active"></i>
					                  </span>
					                  <b class="badge bg-danger pull-right">{{contador_trabajos_sin_ot}}</b>
					                  <i class="fa fa-wrench"></i>
					                  <span>Trabajos</span>
					                </a>
					                <ul class="nav nav-sub dk" style="display: none;">
					                  <li>
					                    <a href="{% url 'erp:ot_new' %}">
					                      <span>Crear Orden</span>
					                    </a>
					                  </li>
					                  <li>
					                    <a href="layout_fullwidth.html">
					                      <span>Evaluar Orden</span>
					                    </a>
					                  </li> 
					                  <li>
										<a href=" {% url 'erp:trabajos' %} ">
											<b class="label bg-info pull-right"></b>
											<span>Listar Trabajos</span>
										</a>

									</li>    
					                </ul>
					              </li>
							</li>
							
							<li class="line dk"></li>

							
							
							
							
							
							
							

							
						</ul>
					</nav>
					<!-- nav -->

					<!-- aside footer -->
					<div class="wrapper m-t">
						<div class="text-center-folded">
							<span class="pull-right pull-none-folded">60%</span>
							<span class="hidden-folded">Milestone</span>
						</div>
						<div class="progress progress-xxs m-t-sm dk">
							<div class="progress-bar progress-bar-info" style="width: 60%;">
							</div>
						</div>
						<div class="text-center-folded">
							<span class="pull-right pull-none-folded">35%</span>
							<span class="hidden-folded">Release</span>
						</div>
						<div class="progress progress-xxs m-t-sm dk">
							<div class="progress-bar progress-bar-primary" style="width: 35%;">
							</div>
						</div>
					</div>
					<!-- / aside footer -->
				</div>
			</div>
		</aside>
		<!-- / aside -->


		<!-- content -->
		<div id="content" class="app-content" role="main">
 			<div class="app-content-body "	>
				{% block content %}  {% endblock %}
			</div>
		</div>
		<!-- /content -->

		<!-- footer -->
		<footer id="footer" class="app-footer" role="footer">
			<div class="wrapper b-t bg-light">
				<span class="pull-right">2.2.0 <a href ui-scroll="app" class="m-l-sm text-muted"><i class="fa fa-long-arrow-up"></i></a></span>
				&copy; 2016 Copyright.
			</div>
		</footer>
		<!-- / footer -->



	</div>

    <!-- jQuery Color for Background Animation -->
    

	<script  type="text/javascript" src="{% static 'libs/jquery/jquery/dist/jquery.js' %}"></script>
	<script  type="text/javascript" src="{% static 'libs/jquery/bootstrap/dist/js/bootstrap.js' %}"></script>
	<script  type="text/javascript" src="{% static 'erp/js/ui-load.js' %}"></script>
	<script  type="text/javascript" src="{% static 'erp/js/ui-jp.config.js' %}"></script>
	<script  type="text/javascript" src="{% static 'erp/js/ui-jp.js' %}"></script>
	<script  type="text/javascript" src="{% static 'erp/js/ui-nav.js' %}"></script>
	<script  type="text/javascript" src="{% static 'erp/js/ui-toggle.js' %}"></script>
	<script  type="text/javascript" src="{% static 'erp/js/ui-client.js' %}"></script>
	<script type="text/javascript" src="{% static 'libs/jquery/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
	<script type="text/javascript" src="{% static 'libs/jquery/bootstrap-datepicker/js/bootstrap-datepicker.es.min.js' %}"></script>
	<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> -->
	<script src="https://code.jquery.com/color/jquery.color-2.1.2.min.js"></script>

	{% block scrypts %}{% endblock %}

</body>
</html>