erp/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'erp'
urlpatterns = [
	
	
    url(r'^$', views.index, name='index'),

    url(r'^misfacturas/$', views.FacturasByUserListView.as_view(), name='mis-facturas'),
    
    
    url(r'^trabajos/$', views.ListarTrabajosView.as_view(), name='trabajos'),
    url(r'^trabajos/ot/new/$', views.ot_new, name='ot_new'),
    url(r'^trabajos/ot/edit/(?P<pk>[0-9]+)/$', views.ot_new, name='ot_new'),


    url(r'^cotizaciones/$', views.ListarCotizacionView.as_view(), name='cotizaciones'),
	url(r'^cotizacion/new/$', views.cotizacion_new, name='cotizacion_new'),
    url(r'^cotizacion/new/documents/(?P<cotizacion_id>[0-9]+)/$', views.documentacion_new, name='cotizacion_new_documents'),
	url(r'^cotizacion/edit/(?P<cotizacion_id>[0-9]+)/$', views.cotizacion_new, name='cotizacion_edit'),
    url(r'^cotizacion/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='cotizacion_detail'),
    url(r'^cotizacion/trabajos/([\w-]+)/$', views.ListarTrabajoCotizacionView.as_view(), name='cotizacion_trabajos'),

    url(r'^factura/new/$', views.factura_new, name='factura_new'),
    url(r'^factura/edit/(?P<factura_id>[0-9]+)/$', views.factura_new, name='factura_new'),
    url(r'^factura/cotizaciones/([\w-]+)/$', views.ListarCotizacionesFacturaView.as_view(), name='cotizaciones_factura'),
    url(r'^facturas/$', views.ListarFacturaView.as_view(), name='facturas'),

    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<cliente_id>[0-9]+)/vote/$', views.vote, name='vote'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Prueba

italuzbi/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
	url(r'^accounts/', include('django.contrib.auth.urls')),
	url(r'^erp/', include('erp.urls')),
    url(r'^admin/', admin.site.urls),
] 

erp/models.py
from __future__ import unicode_literals
from django.db.models import Q

from django.db import models
from django.contrib import admin
from django.utils.encoding import python_2_unicode_compatible
import datetime

from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.	

class Factura(models.Model):
	
	EF = (
		(1,'Impaga'),
		(2,'Pagada'))

	numero = models.IntegerField()
	fecha = models.DateField()
	observacion = models.TextField(null=True)
	created_at = models.DateTimeField(auto_now_add=True, blank=True)
	updated_at = models.DateTimeField(auto_now_add=True, blank=True) 
	created_by = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
	estado = models.IntegerField(choices=EF, default=1)
	cotizaciones = models.ManyToManyField('Cotizacion', null=True, blank=True)

	@property
	def neto(self):
		contador = 0
		for cotizacion in self.cotizaciones.all():
			contador += cotizacion.total
		return contador

	@property
	def iva(self):
		iva = self.neto * 0.19
		return iva

	@property
	def total(self):
		total = self.neto + self.iva
		return total

	def __str__(self):
		return str(self.numero)


class Cliente(models.Model):
	nombre = models.CharField(max_length=200)
	razon_social = models.CharField(max_length=200)
	giro = models.CharField(max_length=200)
	direccion_comercial = models.CharField(max_length=200)
	observacion = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True, blank=True)
	updated_at = models.DateTimeField(auto_now_add=True, blank=True)
	# created_by

	def __str__(self):
		return self.nombre

class Pago(models.Model):
	fecha = models.DateField()
	monto = models.IntegerField()
	facturas = models.ManyToManyField(Factura) 
	created_at = models.DateTimeField(auto_now_add=True, blank=True) 
	updated_at = models.DateTimeField(auto_now_add=True, blank=True)
	# created_by

class Local(models.Model):
	nombre = models.CharField(max_length=200)
	nombre_2 = models.CharField(max_length=200, null=True)
	direccion = models.CharField(max_length=200)
	cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True, blank=True)
	updated_at = models.DateTimeField(auto_now_add=True, blank=True)
	# created_by
	def __str__(self):
		return self.nombre


class Cotizacion(models.Model):
	
	EC = (
		(1, 'En Espera'),
		(2,'Debe'),
		(3,'Por Facturar'),
		(4,'Facturada'))


	fecha = models.DateField()
	estado_cotizacion = models.IntegerField(choices=EC, default=1)
	local = models.ForeignKey(Local, on_delete=models.CASCADE)
	observacion = models.TextField(null=True)
	created_at = models.DateTimeField(auto_now_add=True, blank=True)
	updated_at = models.DateTimeField(auto_now_add=True, blank=True)
	# created_by
	detalle_monto = models.BooleanField()	### <-- Para mostrar o no el detalle de monto por trabajo

	def __str__(self):
		return str(self.id)

	@property
	def neto(self):
		contador = 0
		trabajos = self.trabajo_set.all()
		for trabajo in trabajos: # Trabajo.objects.filter(cotizacion=self):
			contador += trabajo.total
		return contador

	@property
	def iva(self):
		iva = self.neto * 0.19
		return iva

	@property
	def total(self):
		total = self.neto + self.iva
		return total

	@property
	def debe(self):
		return not self.documentacion_set.filter(Q(numero__isnull=True) | Q(fecha__isnull=True)).count()

	@property
	def trabajos_pendientes(self):
		respuesta = 0
		for trabajo in Trabajo.objects.filter(cotizacion=self):
			if trabajo.ot is None:
				respuesta += 1
		return respuesta

	@property
	def tiene_documento(self):
		respuesta = False
		for doc in Documentacion.objects.filter(cotizacion=self):
			if doc.documento:
				respuesta = True
				break
		return respuesta



	def get_absolute_url(self):
		return reverse('erp:cotizacion_edit', kwargs={'cotizacion_id': self.id})



class Encargado(models.Model):
	nombre = models.CharField(max_length=200)
	apellido = models.CharField(max_length=200)
	telefono = models.CharField(max_length=200)
	correo = models.CharField(max_length=200)
	rut = models.CharField(max_length=200)
	cargo = models.CharField(max_length=200)
	cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True, blank=True)
	updated_at = models.DateTimeField(auto_now_add=True, blank=True)
	# created_by

	def __str__(self):
		return self.nombre + " " + self.apellido + " - " + self.cargo + " en " + self.cliente.nombre

class OT(models.Model):
	numero = models.IntegerField()
	fecha = models.DateField()
	encargado = models.ForeignKey(Encargado, on_delete=models.CASCADE)
	observacion = models.TextField(null=True, blank=True)
	created_at = models.DateTimeField(auto_now_add=True, blank=True)
	updated_at = models.DateTimeField(auto_now_add=True, blank=True)
	# created_by

	def __str__(self):
		return str(self.numero) 

class OC(models.Model):  # NO SE OCUPA
	numero = models.IntegerField()
	fecha_emision = models.DateField()
	documento_externo = models.CharField(max_length=50)
	created_at = models.DateTimeField(auto_now_add=True, blank=True)
	updated_at = models.DateTimeField(auto_now_add=True, blank=True)
	# created_by
	cotizaciones = models.ManyToManyField(Cotizacion)

class Actividad(models.Model):
	nombre = models.CharField(max_length=50)
	observacion = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True, blank=True)
	updated_at = models.DateTimeField(auto_now_add=True, blank=True)
	# created_by

	def __str__(self):
		return self.nombre

class Cuadrilla(models.Model):
	nombre = models.CharField(max_length=50)
	observacion = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True, blank=True)
	updated_at = models.DateTimeField(auto_now_add=True, blank=True)
	# created_by
	def __str__(self):
		return self.nombre


class Estructura_costo(models.Model):
	nombre = models.CharField(max_length=200)
	created_at = models.DateTimeField(auto_now_add=True, blank=True)
	updated_at = models.DateTimeField(auto_now_add=True, blank=True)
	# created_by
	def __str__(self):
		return self.nombre


class Cuenta_contable(models.Model):
	nombre = models.CharField(max_length=200)
	estructura_costo = models.ForeignKey(Estructura_costo, on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True, blank=True)
	updated_at = models.DateTimeField(auto_now_add=True, blank=True)
	# created_by
	def __str__(self):
		return self.nombre





class Trabajo(models.Model):
	descripcion = models.CharField(max_length=200)
	unidad = models.IntegerField()
	valor = models.IntegerField()
	actividad = models.ForeignKey(Actividad, on_delete=models.CASCADE)
	cuadrilla = models.ForeignKey(Cuadrilla, on_delete=models.CASCADE)
	cotizacion = models.ForeignKey(Cotizacion, on_delete=models.CASCADE)
	ot = models.ForeignKey(OT, null=True, on_delete=models.CASCADE)
	observacion = models.TextField(null=True, blank=True)
	created_at = models.DateTimeField(auto_now_add=True, blank=True)
	updated_at = models.DateTimeField(auto_now_add=True, blank=True)
	# created_by
	@property
	def total(self):
		return self.valor * self.unidad
	#valor_hora	### <- Para que era?
	def __str__(self):
		return self.descripcion



class Trabajador(models.Model):
	nombre = models.CharField(max_length=200)
	apellido = models.CharField(max_length=200)
	rut = models.CharField(max_length=200)
	telefono = models.CharField(max_length=200)
	correo = models.CharField(max_length=200)
	sueldo_base = models.FloatField()
	cuenta_contable = models.ForeignKey(Cuenta_contable, on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True, blank=True)
	updated_at = models.DateTimeField(auto_now_add=True, blank=True)
	# created_by
	fecha_inicio_contrato = models.DateField()
	fecha_termino_contrato = models.DateField()
	horas_semanales = models.IntegerField()

	def __str__(self):
		return self.nombre + " " + self.apellido

class Ejecuta(models.Model):	### <-- Relacion Trabajador EJECUTA Trabajo
	
	puntaje=(
		(5,'Muy Bien'),
		(4,'Bien'),
		(3,'Suficiente'),
		(2,'Mal'),
		(1,'Muy Mal'))

	trabajo = models.ForeignKey(Trabajo, on_delete=models.CASCADE)
	trabajador = models.ForeignKey(Trabajador, on_delete=models.CASCADE)
	horas_trabajadas = models.IntegerField()
	observacion = models.TextField(null=True, blank=True)
	nota = models.IntegerField(choices=puntaje, default=3)

	def __str__(self):
		return self.trabajo.descripcion + " - " + self.trabajador.nombre + " " + self.trabajador.apellido


class Proveedor(models.Model):
	nombre = models.CharField(max_length=200)
	razon_social = models.CharField(max_length=200)
	giro = models.CharField(max_length=200)
	direccion_comercial = models.CharField(max_length=200)
	observacion = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True, blank=True)
	updated_at = models.DateTimeField(auto_now_add=True, blank=True)
	# created_by


class Material(models.Model):
	nombre = models.CharField(max_length=200)
	unidad = models.CharField(max_length=200)
	sku = models.CharField(max_length=200)
	created_at = models.DateTimeField(auto_now_add=True, blank=True)
	updated_at = models.DateTimeField(auto_now_add=True, blank=True)
	# created_by

class Compra(models.Model):
	numero = models.IntegerField()
	fecha = models.DateField()
	neto = models.IntegerField()
	iva = models.IntegerField()
	proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True, blank=True)
	updated_at = models.DateTimeField(auto_now_add=True, blank=True)
	# created_by
	trabajador = models.ForeignKey(Trabajador, on_delete=models.CASCADE)
	# documento  <- Para que era?????

### <-- Relacion DETALLE de la compra --> ###
class Detalle_compra(models.Model):		
	material = models.ForeignKey(Material, on_delete=models.CASCADE)
	compra = models.ForeignKey(Compra, on_delete=models.CASCADE)
	cantidad = models.IntegerField()



class Utilizado(models.Model):	### <-- Relacion Material UTILIZADO en Trabajo

erp/templates/erp/cotizaciones.html
{% extends "base_generic.html" %}
{% load static %}
{% load humanize %}

{% block title %}Listado de Cotizaciones{% endblock %}

{% block styles %}

<link rel="stylesheet" href="{% static 'libs/jquery/datatables/media/js/datatables.css' %}" type="text/css" />
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.4.2/css/buttons.bootstrap.min.css"></link>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css"></link>



{% endblock styles %}



{% block content %}

<div class="wrapper-md">
  <div class="panel panel-default">
    <div class="panel-heading">
      Listado de Cotizaciones {% if factura %} de <b>Factura #{{factura.numero}}</b> {% endif %}
    </div>
    <div >
      <table id="cotizaciones" class="table table-condensed table-hover b-t b-b" >
        <thead>
          <tr>
            <th>#</th>
            <th>Fecha</th>
            <th>Local</th>
            <th>Trabajo</th>
            <th>Estado</th>
            <th>Pendientes</th>
            <th>Neto</th>
            <th>IVA</th>
            <th>Total</th>
            <th>Accion</th>
          </tr>
        </thead>
        <tbody>
          {% for cotizacion in cotizacion_list %} 
            <tr>
              <td><a href="{% url 'erp:cotizacion_trabajos' cotizacion.pk %}" class="text-info" style="text-decoration: underline;">{{cotizacion.pk}}</a></td>
              <td>{{cotizacion.fecha|date:"SHORT_DATE_FORMAT" }}</td>
              <td>{{cotizacion.local}} - {{cotizacion.local.cliente}}</td>
              <td>{{cotizacion.trabajo_set.first.actividad }}</td>
              <td> 
                {% if cotizacion.estado_cotizacion == 1 %} <label class="label label-info m-l-xs"><a href="#" style="cursor:pointer;">{{cotizacion.get_estado_cotizacion_display}}</a></label> 
                {% elif cotizacion.estado_cotizacion == 2 %}<label class="label label-warning m-l-xs"><a href="{% url 'erp:cotizacion_new_documents' cotizacion.pk %}">{{cotizacion.get_estado_cotizacion_display}} <i class="fa fa-hand-o-left"></i></a></label> 
                {% elif cotizacion.estado_cotizacion == 3 %}<label class="label label-danger m-l-xs"><a href="#" style="cursor:pointer;">{{cotizacion.get_estado_cotizacion_display}}</a></label>
                {% else %}<label class="label label-primary m-l-xs">{{cotizacion.get_estado_cotizacion_display}}</label> 
                {% endif %}
              </td>
              <td>
                {% if cotizacion.trabajos_pendientes > 0 %} <label class="badge bg-danger">{{cotizacion.trabajos_pendientes}}</label> 
                {% else %}<label class="badge bg-success">{{cotizacion.trabajos_pendientes}}</label> 
                {% endif %}
              </td>

              


              <td>${{cotizacion.neto|floatformat:"0"|intcomma }}</td>
              <td>${{cotizacion.iva|floatformat:"0"|intcomma }}</td>
              <td>${{cotizacion.total|floatformat:"0"|intcomma }}</td>
              <td class="text-center">
                <a href="{% url 'erp:cotizacion_edit' cotizacion.pk %}"><i class="fa fa-pencil icon text-inverse"></i></a>
                <a href="{% url 'erp:cotizacion_detail' pk=cotizacion.pk %}"><i class="fa fa-search icon text-primary"></i></a>
                <a href="{% url 'erp:cotizacion_detail' pk=cotizacion.pk %}"><i class="fa fa-file-pdf-o icon text-inverse"></i></a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>


{% block scrypts %}
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>

<script type="text/javascript" src="{% static 'libs/jquery/datatables/media/js/datatables.js' %}"></script>
<script src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.bootstrap.min.js"></script>

<script type="text/javascript">
  $(document).ready(function() {
    $('#cotizaciones').DataTable( {
        "order": [[ 0, "desc" ]],
        "language": {
                "sProcessing":     "Procesando...",
                "sLengthMenu":     "Mostrar _MENU_ registros",
                "sZeroRecords":    "No se encontraron resultados",
                "sEmptyTable":     "Ningún dato disponible en esta tabla",
                "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix":    "",
                "sSearch":         "Buscar:",
                "sUrl":            "",
                "sInfoThousands":  ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst":    "Primero",
                    "sLast":     "Último",
                    "sNext":     "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            }
    } );
} );
</script>



{% endblock %}







{% endblock %}

erp/templates/erp/detail.html
{% extends "base_generic.html" %}
{% load humanize %}
{% block title %}Detalle de la Cotización{% endblock %}
{% block content %}


	    
<div class="wrapper-md">
  <div>
    <div class="row">
      <div class="col-xs-12">
      	<h1 class="m-n font-thin h3 text-center">Cotización #{{ object.id }}</h1>
        
      </div>
      <div class="col-xs-6 text-right">
            
      </div>
    </div>
    <div class="well m-t bg-light lt">
      <div class="row">
        <div class="col-xs-6">
          <strong>Mandante: {{ object.local.cliente.nombre }}</strong>
          <p>
            Atención: Servicios Italuz <br>
            Local: {{ object.local }}<br>
            Obra: Mantenciones <br>
            
          </p>
        </div>
        <div class="col-xs-6" style="text-align: right;">
          <strong>SERVICIOS ITALUZ LTDA. | Obras Civiles Menores</strong>
          <p>
            Rut: 76.174.518-2<br>
            Dirección: Paseo Ahumada 11 Of. 309<br>
            Santiago, Chile<br>
            Teléfonos: +56 9 88190591<br>
            Correo: servicios.italuz@gmail.com<br>
          </p>
        </div>
      </div>
    </div>
    <p class="m-t m-b">Fecha Cotización: <strong>{{ object.fecha }}</strong><br>
        Estado Cotizacion: 
          {% if cotizacion.estado_cotizacion == 1 %} <label class="label label-info m-l-xs">{{cotizacion.get_estado_cotizacion_display}}</label> 
          {% elif cotizacion.estado_cotizacion == 2 %}<label class="label label-warning m-l-xs">{{cotizacion.get_estado_cotizacion_display}}</label> 
          {% elif cotizacion.estado_cotizacion == 3 %}<label class="label label-danger m-l-xs">{{cotizacion.get_estado_cotizacion_display}}</label>
          {% else %}<label class="label label-primary m-l-xs">{{cotizacion.get_estado_cotizacion_display}}</label> 
          {% endif %}
          {% if cotizacion.debe %}
          <ul>
                    {% for documento in cotizacion.documentacion_set.all %}
                      <li>{{ documento.documento }} #{{documento.numero}} - {{documento.fecha|date:"SHORT_DATE_FORMAT"}} </li>
                    {% empty %}
                      no tiene documentos asociados
                    {% endfor %}
          </ul>
          {% endif %}
        <br>
    </p>
    <div class="line"></div>
    <table class="table table-striped bg-white b-a">
      <thead>
        
        <tr>
          <th style="width: 60px">ITEM</th>
          <th>DESCRIPCIÓN</th>
          <th style="width: 90px">UNIDADES</th>
          <th style="width: 150px">VALOR UNITARIO</th>
          <th style="width: 120px">VALOR TOTAL</th>
        </tr>

      </thead>
      <tbody>
      {% if object.trabajo_set.all %}
        {% for trabajo in object.trabajo_set.all %} 
        <tr>
			<td style="text-align: center;">{{ forloop.counter }}</td>
			<td>{{ trabajo.descripcion }}</td>
			<td style="text-align: center;">{{ trabajo.unidad }}</td>
			<td style="text-align: right;">${{ trabajo.valor|intcomma }}</td>
			<td style="text-align: right;">${{ trabajo.total|intcomma }}</td>
        </tr>
        {% endfor %}
      {% else %}
		<p>No tiene trabajos asociados.</p>
	  {% endif %}
        <tr>
          <td colspan="4" class="text-right"><strong>Subtotal</strong></td>
          <td style="text-align: right;">${{ object.neto|floatformat:"0"|intcomma }}</td>
        </tr>

        <tr>
          <td colspan="4" class="text-right no-border"><strong>IVA</strong></td>
          <td style="text-align: right;">${{ object.iva|floatformat:"0"|intcomma }}</td>
        </tr>
        <tr>
          <td colspan="4" class="text-right no-border"><strong>Total</strong></td>
          <td style="text-align: right;"><strong>${{ object.total|floatformat:"0"|intcomma }}</strong></td>
        </tr>
      </tbody>
    </table>

    <div class="col-xs-6">



        <p>{{ object.observacion|linebreaks }}
        </p>
      </div>

  </div>
</div>







{% endblock content %}

erp/templates/erp/facturas.html
{% extends "base_generic.html" %}
{% load static %}
{% load humanize %}

{% block title %}Listado de Facturas{% endblock %}

{% block styles %}

<link rel="stylesheet" href="{% static 'libs/jquery/datatables/media/js/datatables.css' %}" type="text/css" />
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.4.2/css/buttons.bootstrap.min.css"></link>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css"></link>



{% endblock styles %}



{% block content %}

<div class="wrapper-md">
  <div class="panel panel-default">
    <div class="panel-heading">
      Listado de Facturas
    </div>
    <div >
      <table id="cotizaciones" class="table table-condensed table-hover b-t b-b" >
        <thead>
          <tr>
            <th>#</th>
            <th>Fecha</th>
            <th>Cliente</th>
            <th>Estado</th>
            <th>Neto</th>
            <th>IVA</th>
            <th>Total</th>
            <th>Accion</th>
          </tr>
        </thead>
        <tbody>
          {% for factura in factura_list %} 
            <tr>
              <td><a href="{% url 'erp:cotizaciones_factura' factura.pk %}" class="text-info" style="text-decoration: underline;">{{factura.numero}}</a></td>
              <td>{{factura.fecha|date:"SHORT_DATE_FORMAT" }}</td>
              <td>{{factura.cotizaciones.first.local.cliente}}</td>
              <td> 
                {% if factura.estado == 1 %} <label class="label bg-danger m-l-xs"><a href="#" style="cursor:pointer;">{{factura.get_estado_display}}</a></label> 
                {% else %}<label class="label label-primary m-l-xs">{{factura.get_estado_display}}</label> 
                {% endif %}
              </td>
              <td>${{factura.neto|floatformat:"0"|intcomma }}</td>
              <td>${{factura.iva|floatformat:"0"|intcomma }}</td>
              <td>${{factura.total|floatformat:"0"|intcomma }}</td>
              <td class="text-center">
                <a href="{% url 'erp:factura_new' factura.pk %}"><i class="fa fa-pencil icon text-inverse"></i></a>
                <a href="#"><i class="fa fa-search icon text-primary"></i></a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>


{% block scrypts %}
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>

<script type="text/javascript" src="{% static 'libs/jquery/datatables/media/js/datatables.js' %}"></script>
<script src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.bootstrap.min.js"></script>

<script type="text/javascript">
  $(document).ready(function() {
    $('#cotizaciones').DataTable( {

    
        "language": {
                "sProcessing":     "Procesando...",
                "sLengthMenu":     "Mostrar _MENU_ registros",
                "sZeroRecords":    "No se encontraron resultados",
                "sEmptyTable":     "Ningún dato disponible en esta tabla",
                "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix":    "",
                "sSearch":         "Buscar:",
                "sUrl":            "",
                "sInfoThousands":  ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst":    "Primero",
                    "sLast":     "Último",
                    "sNext":     "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            }
    } );
} );
</script>



{% endblock %}







{% endblock %}

erp/templates/erp/facturas_por_usuario.html
{% extends "base_generic.html" %}
{% load humanize %}

{% block content %}
    <h1>Facturas</h1>

    {% if factura_list %}
    <ul>

      {% for factura in factura_list %} 
      <li>
        <a href="{% url 'erp:factura_new' factura.pk %}">#{{factura.numero}} - ${{factura.neto|floatformat:"0"|intcomma}} </a> 
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No tiene facturas creadas.</p>
    {% endif %}       
{% endblock %}

erp/templates/erp/index.html
{% extends "base_generic.html" %}

{% block title%} Hola Mundo {% endblock %}


{% block content %}
Hola Mundo 2
{% endblock content %}

erp/templates/erp/results.html
<h1>{{ cliente.nombre_cliente }}</h1>

<ul>
{% for factura in cliente.factura_set.all %}
    <li>Factura Nº {{ factura.numero_factura }} -- {{ factura.estado }} </li>
{% endfor %}
</ul>

<a href="{% url 'erp:detail' cliente.id %}">Pagar mas facturas?</a>